// Copyright (c) .NET Foundation. All rights reserved.
// Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.

namespace Alethic.AspNetCore.EcmaScript.SpaServices.Prerendering;

/// <summary>
/// Describes the prerendering result returned by JavaScript code.
/// </summary>
internal class PrerendererResult
{

	/// <summary>
	/// The HTML generated by the prerendering logic.
	/// </summary>
	public string? Html { get; set; }

	/// <summary>
	/// If set, specifies that instead of rendering HTML, the response should be an HTTP redirection to this URL.
	/// This can be used if the prerendering code determines that the requested URL would lead to a redirection according
	/// to the SPA's routing configuration.
	/// </summary>
	public string? RedirectUrl { get; set; }

	/// <summary>
	/// If set, specifies the HTTP status code that should be sent back with the server response.
	/// </summary>
	public int? StatusCode { get; set; }

}
